# Generated by Django 2.2 on 2019-04-17 09:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190417_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 17, 9, 41, 57, 134346, tzinfo=utc)),
        ),
    ]
