# Generated by Django 2.2 on 2019-04-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190417_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
